routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardProdukController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use App\Models\Category;
use App\Models\Produk;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// halaman Index Utama
Route::get('/', function () {
    return view('index', [
        'categories' => Category::all(),
        'produks' => Produk::all()
    ]);
});

// halaman menampilkan Semua Produk
Route::get('/produk', function(){
    return view('produks', [
        'categories' => Category::all(),
        'produks' => Produk::all()
    ]);
});

// Login and Logout Route
Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate'])->name('authenticate');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
// End Login and Logout Route


// Register Route
Route::get('/register', [RegisterController::class, 'index']);
Route::post('/register', [RegisterController::class, 'store']);
// End Of Register Route


Route::get('/dashboard', function(){
    return view('dashboard.index');
})->middleware('auth')->name('dashboard');


// Produk pada Dashboard Route
Route::resource('/dashboard/produk', DashboardProdukController::class)->middleware('auth')->except('show');

// cart
Route::resource('/cart', CartController::class)->middleware('guest');

// admin Category
Route::resource('/dashboard/categories', CategoryController::class)->except('show')->middleware('master');

// user Controller
Route::resource('/dashboard/user', UserController::class)->except('show', 'create')->middleware('master');

resources/views/index.blade.php
@extends('layouts.main')
@section('content')
    
@include('partials.carousel')

@include('partials.category')

@include('partials.produkindex')




{{-- more button --}}
<div class="container text-center my-4">
    <a href="/produk" class="btn btn-warning btn-lg"> More...</a>
</div>
{{-- more button end --}}






@endsection

resources/views/produks.blade.php
@extends('layouts.main')
@section('content')
    
{{-- header --}}
<div class="container mt-3">
    <div class="row text-center">
        <div class="col-lg-12">
            <h1>
                Detail Semua Produk
            </h1>
            <hr>
        </div>
    </div>
</div>
{{-- header End --}}

{{-- category --}}
<div class="container mt-3">
    <div class="row text-center">
        <div class="col-lg-12">
            <h1>
                Category
            </h1>

        </div>
    </div>
</div>
<div class="container mt-3">
    <div class="row text-center">
        <div class="btn-group btn-group-toggle col-md-12" data-toggle="buttons">
          @foreach($categories as $category)
            <label class="btn btn-secondary ">
              <a href="#" class="text-decoration-none  text-light"> {{ $category->name }}</a>
            </label>
            @endforeach
        </div>
    </div>
</div>
<hr>
  {{-- category end --}}

{{-- Produk All --}}
<div class="container-fluid ">
    <div class="row d-flex justify-content-around">
   
     
   @foreach($produks as $produk)
   <div class="card text-center m-3 col-md-2" style="width: 18rem;">
       <img src="{{ asset('storage/' . $produk->image) }}" class="card-img-top" alt="...">
       <div class="card-body ">
         <h5 class="card-title"><a href="" class="text-decoration-none text-dark">{{ $produk->name }}</a></h5>
         <p class="card-text">{!! $produk->body !!}</p>
         <p class="card-text">Rp. {{ $produk->harga }}</p>
         <p class="card-text">Stock: {{ $produk->stock }}</p>

         <div class="container">
            <div class="row">
              <form action="{{ route('cart.store') }}" class="form-inline" method="post">
                @csrf
                <input type="hidden" name="produk_id" value="{{ $produk->id }}">
                <label for="qty"></label>
                <input type="number" class="form-control col-md-4 m-1" name="qty" id="qty">
                <button type="submit" class="btn btn-primary btn-sm col-md-4 m-1">Add To Cart</button>
              </form>
            </div>
          </div>
       
       </div>
     </div>
   @endforeach
  
   
   
   </div>
   </div>

{{-- produk end --}}





@endsection